### ISSUE TITLE
Afew in gentoo

### ISSUE THREAD

**Issue by GuillaumeSeren** [teythoon/afew#113]
Hey there,
I have some problem using afew in a gentoo system, it is a migration of my mail stack I used elsewhere, so I have some data but the error is new, I use afew to tag and move mails:
$ afew --tag --new -vv
DEBUG:root:Executing query '(tag:new)'
DEBUG:root:executing ['dbacl', '-T', 'email', '-c', '/dir/afew/categories/spam', '-c', '/dir/afew/categories/reference_category', '-n']
WARNING:afew.filters.ClassifyingFilter.ClassifyingFilter:Classification failed: dbacl classification failed:
b'dbacl:error: not a dbacl 1.14 dlw portable category file [/dir/afew/categories/reference_category]\ndbacl:error: could not load category /dir/afew/categories/reference_category\n'
afew -U    
afewTraceback (most recent call last):
  File "/usr/lib64/python3.4/email/_encoded_words.py", line 109, in decode_b
    return base64.b64decode(padded_encoded, validate=True), defects
  File "/usr/lib64/python3.4/base64.py", line 89, in b64decode
    raise binascii.Error('Non-base64 digit found')
binascii.Error: Non-base64 digit found

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/dir/afew", line 9, in <module>
    load_entry_point('afew==0.0.0', 'console_scripts', 'afew')()
  File "/dir/.local/lib64/python3.4/site-packages/afew-0.0.0-py3.4.egg/afew/commands.py", line 205, in main
    inner_main(options, database, query_string)
  File "/dir/.local/lib64/python3.4/site-packages/afew-0.0.0-py3.4.egg/afew/main.py", line 63, in main
    all_messages = list(database.mail_bodies_matching(query_string))
  File "/dir/.local/lib64/python3.4/site-packages/afew-0.0.0-py3.4.egg/afew/Database.py", line 128, in mail_bodies_matching
    yield extract_mail_body(message)
  File "/dir/.local/lib64/python3.4/site-packages/afew-0.0.0-py3.4.egg/afew/utils.py", line 100, in extract_mail_body
    raw_payload = part.get_payload(decode=True)
  File "/usr/lib64/python3.4/email/message.py", line 287, in get_payload
    value, defects = decode_b(b''.join(bpayload.splitlines()))
  File "/usr/lib64/python3.4/email/_encoded_words.py", line 124, in decode_b
    raise AssertionError("unexpected binascii.Error")
AssertionError: unexpected binascii.Error

What do you think, maybe I missed something ?

**Comment by GuillaumeSeren** [comment]
Ok I find the problem gentoo use last version of python (v3.4.3) so you can use python v2 by reinstalling it using the alias python2 instead of just python then it will work.

Sorry for the noise I close the issue.
